apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: prod
  labels:
    role: backend
    env: demo
spec:
  type: NodePort  # Service type set to NodePort
  ports:
    - port: 4800        # Port that the service will expose
      targetPort: 4800  # Port on the pod where the app is running
      protocol: TCP
      nodePort: 30000    # Optional: Specify a custom NodePort (between 30000-32767), or let Kubernetes assign one
  selector:
    role: backend  # Match the labels of the backend pods

